# Generated by Buildr 1.3.5, change to your liking
# Version number for this release
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "seams"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

desc "The Seams Determination project"
define "seams" do
  project.version = VERSION_NUMBER
  project.group = GROUP
  compile.with 'lib/javaparser-1.0.8.jar', 'lib/jgraphx.jar', 'log4j:log4j:jar:1.2.14'
  manifest["Implementation-Vendor"] = COPYRIGHT
  package(:jar)
  test.using :testng
end
